name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: V2rayNG
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Fetch AndroidLibXrayLite tag
      run: |
        cd ../AndroidLibXrayLite
        CURRENT_TAG=$(git describe --tags --abbrev=0)
        echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
        
    - name: Download libv2ray
      uses: robinraju/release-downloader@v1.13
      with:
        repository: '2dust/AndroidLibXrayLite'
        tag: ${{ env.CURRENT_TAG }}
        fileName: 'libv2ray.aar'
        out-file-path: V2rayNG/app/libs/
        
    - name: Build Debug APK
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Saturn7-VPN-Debug
        path: V2rayNG/app/build/outputs/apk/debug/app-debug.apk
