name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-java@v5
      with:
        java-version: '17'
    - uses: android-actions/setup-android@v4
    - run: |
        cd AndroidLibXrayLite
        echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - uses: robinraju/release-downloader@v1.13
      with:
        repository: '2dust/AndroidLibXrayLite'
        tag: ${{ env.TAG }}
        fileName: 'libv2ray.aar'
        out-file-path: V2rayNG/app/libs/
    - run: |
        cd V2rayNG
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        chmod +x gradlew
        ./gradlew assembleDebug
    - run: |
        find V2rayNG/app/build/outputs/apk -name "*.apk"
    - uses: actions/upload-artifact@v4
      with:
        name: Saturn7-VPN
        path: V2rayNG/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
